plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.9.0'
    id 'java'
    id 'jacoco'
}
apply plugin: 'application'
mainClassName = 'org.example.core.Main'
group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.apache.ivy:ivy:2.5.1' // Добавьте эту строку
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
    implementation 'org.codehaus.groovy:groovy-all:3.0.9'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.22'
}

sourceSets {
    main.java.srcDirs += ['src/main/java', 'src/main/kotlin']
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

kotlin {
    jvmToolchain(17) // вместо 21
}
jacocoTestReport {
    reports {
        xml.required = true
    }
}
